name: terraform-CI

on:
  push:
    branches:
      - main

jobs:
    IAC:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan

    - name: Terraform Apply
      if: success()
      run: terraform apply -auto-approve plan.tfplan

    - name: wait for 5 minutes to check the resources created
      run: sleep 300

    - name: Terraform Destroy
      run: terraform destroy -auto-approve

        